### ISSUE TITLE
Add options for host and checkout

### ISSUE THREAD

**Issue by skudlur** [acmpesuecc/gegit#1]
# Description
Check this struct out [here](https://github.com/skudlur/gegit/blob/610417a1de90630206d7d901c292f88417858592/src/main.rs#L11C1-L23C2). 

There are two struct values "host" and "checkout" that need some functionality configured. 

* Host refers to the hosted service i.e. Github, Gitlab or Codeberg.
* Checkout refers to the tags or branches that the user can specify to pull/clone a particular tag/branch.

**Comment by n1haldev** [comment]
Can I be assigned this?

**Comment by skudlur** [comment]
@n1haldev assigned

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by Alley2717** [comment]
can i try
