### ISSUE TITLE
Add tests to check if SSH is not configured

### ISSUE THREAD

**Issue by skudlur** [acmpesuecc/gegit#2]
# Description
Add some tests that run after the installation of gegit to ensure the user has an SSH key setup. 

Take a look at [this](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for reference.

# Note
* Brownie points if you can automate the ssh-keygen (via a CLI option, post installation) if SSH is not setup.

**Comment by skandesh-kk** [comment]
assign me this issue

**Comment by skudlur** [comment]
@skandesh-kk assigned

**Comment by sujay1844** [comment]
please assign me this issue if @skandesh-kk doesn't solve it

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by Alley2717** [comment]
can i try
