### ISSUE TITLE
Add feature to clone non-personal (public) repos

### ISSUE THREAD

**Issue by skudlur** [acmpesuecc/gegit#3]
# Description
At the moment, gegit can only fetch personal repos (based on host git.config), Add a feature to enable users to fetch any repo by addressing `uname/reponame`.

**Comment by skudlur** [comment]
@nuove assigned

**Comment by Ritwik-Ag** [comment]
can u assign me

**Comment by SafwanAhmed08** [comment]
can i get this assigned

**Comment by Alley2717** [comment]
can i try

**Comment by ssether04** [comment]
can i get assigned if this is still open?

**Comment by rithulkamesh** [comment]
can i get this assigned

**Comment by skudlur** [comment]
@rithulkamesh assigned

**Comment by rithulkamesh** [comment]
#10

**Comment by RishavSinha20** [comment]
if this is still open can  i get assigned?
